vidly/employee/urls.py
from django.urls import path
from . import views

app_name='employee'
urlpatterns=[
    path('',views.index,name='index'),
    path('<int:employee_id>',views.detail,name='detail'),
]

vidly/vidly/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employee/', include('employee.urls')),
    path('',views.home),
]

vidly/employee/models.py
# Create your models here.
from django.db import models

class Employee_data(models.Model):
    name=models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Employee(models.Model):
    employee_name=models.CharField(max_length=255)

    designation=models.CharField(max_length=255)
    phone_number=models.IntegerField()
    address=models.CharField(max_length=255)

vidly/employee/views.py
# Create your views here.
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404
from .models import Employee

# Create your views here.
def index(request):
    employee=Employee.objects.all()
    return render(request,'employee/index.html',{'employee':employee})
def detail(request,employee_id):

    employee=get_object_or_404(Employee,pk=employee_id)
    return render(request,'employee/detail.html',{'employee':employee})

vidly/vidly/views.py
from django.shortcuts import render

def home(request):
    return render(request,'home.html')

vidly/employee/templates/employee/detail.html
{% extends 'base.html' %}

{% block content %}
<dl>
    <dt>Employee Name</dt>
    <dd>{{employee.employee_name}}</dd>

    <dt>Designation</dt>
    <dd>{{employee.designation}}</dd>
</dl>
{% endblock %}

vidly/employee/templates/employee/index.html
{% extends 'base.html' %}

{% block content %}

<html>
<head>
</head>
<body>
<table class="table table-hover">
    <thead>
        <tr>
            <th>Name</th>
            <th>Designation</th>
            <th>Phone</th>
            <th>Address</th>


        </tr>
    </thead>
    <tbody>
    {% for employee in  employee %}
        <tr>

            <td>{{employee.employee_name}}</td>
            <td>{{employee.designation}}</td>
            <td>{{employee.phone_number}}</td>
            <td>{{employee.address}}</td>

        </tr>

    {% endfor %}

    </tbody>
</table>
{% endblock %}
</body>
</html>

vidly/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Vidly</title>
  </head>
  <body>
      <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="#">Employee Database</a>
      </nav>
      <main class="container">
        {% block content %}
        {% endblock %}
      </main>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

vidly/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'employee:index' %}">Database</a>
{% endblock %}